name: Release-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet Source/Code/CannedBytes.sln restore
    - name: Build
      run: dotnet Source/Code/CannedBytes.sln build --configuration Release --no-restore
    - name: Test
      run: dotnet Source/Code/CannedBytes.sln test --no-restore --verbosity normal
